# for example admin
username = "demo" 

# for example: vn9dPdQOau7HRONvzXGL3XCg without spaces
password = "CdzXMFkzfc7xq44WgRe1rpLq" 

# for example https://mytestingsite.com
site_url = "https://s-q2qy7qpaq7czl.eu1.wpsandbox.org"

