title = "Testing Program"

# enter categories names in the list as ["cat name1", "cat name2"]
categories = ["best games", "worst games"] 

# enter categories names in the list as ["tag1", "tag2"]
tags = ["best games", "worst games"]

featured_media_path = ""

content_path = "" # optional if you want the content from a file

content = """
this is a testing content
"""

